version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run: ls && date
    - run: date
    - run: date
    - run: date
    - run: ls && date

workflows:
  version: 2
  abas:
    jobs:
    - abas
